-- Insert all live features into product_roadmap
INSERT INTO product_roadmap (title, description, status, category, priority, upvotes, downvotes, order_index) VALUES
('Telegram Bot Integration', 'Complete Telegram bot setup with webhook configuration, DM and group chat support, and automated bot deployment workflow.', 'completed', 'platform', 'high', 0, 0, 1),
('AI Chat & Conversations', 'Full-featured AI chat system with message history, conversation tracking, topic detection, and multi-user support.', 'completed', 'foundation', 'high', 0, 0, 2),
('Custom Tools System', 'API integration builder allowing communities to connect external APIs, test endpoints, monitor usage, and view execution logs.', 'completed', 'developer_tools', 'high', 0, 0, 3),
('Community Management', 'Create and manage communities with member roles, privacy settings, invite codes, and admin controls.', 'completed', 'foundation', 'high', 0, 0, 4),
('Memory Management', 'Store and organize AI memories for each community member to enable personalized interactions and context-aware responses.', 'completed', 'foundation', 'high', 0, 0, 5),
('Agent Configuration', 'Configure AI behavior with customizable model selection, temperature, token limits, system instructions, and personality settings.', 'completed', 'foundation', 'high', 0, 0, 6),
('Analytics Dashboard', 'Track message volume, AI costs, token usage, conversation metrics, and community engagement statistics.', 'completed', 'analytics', 'medium', 0, 0, 7),
('Telegram User Management', 'View and manage Telegram users, track message counts, engagement metrics, and user preferences.', 'completed', 'platform', 'medium', 0, 0, 8),
('Daily Automated Messages', 'Schedule automated daily messages to community members with timezone support and customizable content.', 'completed', 'user_experience', 'medium', 0, 0, 9),
('Broadcast Messaging', 'Send broadcast messages to all community members or filtered groups with delivery tracking and analytics.', 'completed', 'user_experience', 'medium', 0, 0, 10),
('Voice Interface', 'ElevenLabs voice agent integration for natural voice conversations with AI agents.', 'completed', 'integrations', 'medium', 0, 0, 11),
('Webhook System', 'External webhook integration allowing third-party services to trigger bot actions and receive updates.', 'completed', 'developer_tools', 'medium', 0, 0, 12),
('Token Launch Integration', 'Launch community tokens via Long.xyz with automatic deployment, metadata upload, and transaction tracking.', 'completed', 'integrations', 'high', 0, 0, 13),
('Roadmap Voting System', 'Public product roadmap with upvote/downvote functionality, status tracking, and community feedback.', 'completed', 'user_experience', 'medium', 0, 0, 14),
('User Authentication', 'Secure user authentication with email/password, password reset, and session management via Supabase Auth.', 'completed', 'foundation', 'high', 0, 0, 15),
('AI Context Viewer', 'Debug view showing complete AI context including memories, user data, system prompts, and conversation history.', 'completed', 'developer_tools', 'low', 0, 0, 16),
('Bot Health Monitoring', 'Real-time bot connection status monitoring with automatic health checks and reconnection capabilities.', 'completed', 'platform', 'medium', 0, 0, 17),
('Conversation Analytics', 'Track conversation topics, participant counts, message frequency, and engagement patterns across chats.', 'completed', 'analytics', 'medium', 0, 0, 18),
('Proactive Outreach', 'AI-driven proactive messaging system that reaches out to users based on inactivity or engagement triggers.', 'completed', 'user_experience', 'medium', 0, 0, 19),
('LangSmith Integration', 'Built-in LangSmith integration for AI conversation tracing, debugging, and performance monitoring.', 'completed', 'developer_tools', 'medium', 0, 0, 20),
('Community Join Requests', 'Request and approval system for private communities with admin moderation and notification system.', 'completed', 'platform', 'medium', 0, 0, 21),
('Auto-Generated Intros', 'Automatically generate user introduction messages from their chat history and activity patterns.', 'completed', 'user_experience', 'low', 0, 0, 22),
('AI Bio Generation', 'Generate personalized user bios using AI based on message content and user interactions.', 'completed', 'user_experience', 'low', 0, 0, 23),
('Profile Data Parser', 'Parse unstructured memory data into structured user profile fields with AI-powered extraction.', 'completed', 'foundation', 'low', 0, 0, 24),
('Multi-Model Support', 'Support for multiple AI models including GPT-4, Claude, and other LLMs with dynamic model switching.', 'completed', 'foundation', 'high', 0, 0, 25),
('Community Favorites', 'Allow users to favorite communities for quick access and personalized community discovery.', 'completed', 'user_experience', 'low', 0, 0, 26),
('Token Analytics', 'Track token holder statistics, transaction history, and community token economics metrics.', 'completed', 'analytics', 'medium', 0, 0, 27),
('Custom Tool Logs', 'Detailed execution logs for custom tools showing inputs, outputs, errors, and performance metrics.', 'completed', 'developer_tools', 'medium', 0, 0, 28),
('Workflow Automation', 'Configure automated workflows for common community tasks like onboarding, notifications, and member provisioning.', 'completed', 'platform', 'medium', 0, 0, 29),
('Profile Claim System', 'Allow users to claim their Telegram-created profiles with verification codes and email confirmation.', 'completed', 'foundation', 'medium', 0, 0, 30);